### ISSUE TITLE
ruby-build through boxen script fails to build 2.1.1

### ISSUE THREAD

**Issue by seanknox** [boxen/puppet-ruby#102]
Tried to install Boxen on a fresh OS X 10.9 system with Xcode CLT `5.1.0.0.1.1396320587`.

When I `rbenv install 2.1.1` from the command line, it works. Running through boxen generates this error, complaining that `/opt/X11/lib` doesn't exist (it doesn't).
```
Debug: Executing '/opt/boxen/ruby-build/bin/ruby-build 2.1.1 /opt/rubies/2.1.1'
Error: install failed with a crazy error: Execution of '/opt/boxen/ruby-build/bin/ruby-build 2.1.1 /opt/rubies/2.1.1' returned 1: Installing yaml-0.1.6...
Installed yaml-0.1.6 to /opt/rubies/2.1.1

Installing openssl-1.0.1g...
Installed openssl-1.0.1g to /opt/rubies/2.1.1

Installing ruby-2.1.1...
mkdir: /opt/X11/lib: Permission denied

BUILD FAILED

```

**Comment by seanknox** [comment]
@dgoodlad can you explain or point to somewhere that explains why xquartz is necessary for puppet-ruby?

**Comment by dgoodlad** [comment]
Older Rubies used to require X11 to build via ruby-build, but the default build options now disable the `tk` library which was the main reason X11 was necessary. I think it would be reasonable to remove that dependency completely, now.

**Comment by seanknox** [comment]
Thanks @dgoodlad, PR to remove XQuartz dependency up at https://github.com/boxen/puppet-ruby/pull/130.

**Comment by akoinesjr** [comment]
@seanknox Thank you, your solution fixed this issue for me.

**Comment by seanknox** [comment]
Just ran on a fresh install of Yosemite with CLT 6.3.1 and everything checked out. Thanks to all who helped.
