### ISSUE TITLE
current-ruby not a valid identifier

### ISSUE THREAD

**Issue by dougalcorn** [boxen/puppet-ruby#113]
I'm not sure why/when this broke. I'm in the process of upgrading `puppet-ruby` from  7.2.4 to 8.1.2. When I run the `boxen` command, I get this output:

```
Notice: /Stage[main]/Projects::Icurio2/Exec[bundle install icurio2]/returns: /opt/boxen/env.d/30_ruby.sh: line 17: `current-ruby': not a valid identifier
Error: env -i sh -c 'source /opt/boxen/env.sh && RBENV_VERSION=2.0.0-p451 bundle install --path vendor' returned 2 instead of one of [0]
Error: /Stage[main]/Projects::Icurio2/Exec[bundle install icurio2]/returns: change from notrun to 0 failed: env -i sh -c 'source /opt/boxen/env.sh && RBENV_VERSION=2.0.0-p451 bundle install --path vendor' returned 2 instead of one of [0]
```

`Icurio2` is one of my rails projects. I'm not sure how to proceed on this.

**Comment by seanknox** [comment]
@dougalcorn I believe the problem is `bash` functions names can contain dashes, while `sh` (POSIX-compliant) doesn't allow for them. Think the quick fix would be to rename `current-ruby` to `current_ruby`. @dgoodlad does that sound right?

**Comment by seanknox** [comment]
Yep, seems to be the case. Solution is to change the dash to an underscore. http://stackoverflow.com/questions/2821043/allowed-characters-in-linux-environment-variable-names

**Comment by dgoodlad** [comment]
Thanks for debugging this @seanknox !
