### ISSUE TITLE
Add gem install support to optional params

### ISSUE THREAD

**Issue by marzapower** [boxen/puppet-ruby#58]
I am developing an app that uses `therubyracer` gem and thus the `libv8` gem.

In most cases the installation of the `libv8` gem will have strange output errors (see http://stackoverflow.com/questions/16514758/gem-install-libv8-version-3-11-8-17-on-ruby-windows). The most common solution is to install `v8` via homebrew and then install the gem forcing the use of the local installation of `v8`. This must be done with the `-- --with-system-v8` option to the `gem install` command.

Would it make sense to add this options to the tool?

**Comment by seanknox** [comment]
Hi is this still an issue?

**Comment by marzapower** [comment]
Hi @seanknox, honestly I think it is not. I reinstalled my machine a couple of times and with different versions of OS X and I don't recall noticing this issue in this last year.

**Comment by seanknox** [comment]
Thanks—feel free to re-open if you encounter it again.
