### ISSUE TITLE
Problem running bundler commands: hub alias: unknown shell

### ISSUE THREAD

**Issue by seanknox** [boxen/puppet-ruby#79]
I'm trying to run `bundler` commands within a Rails app but getting a `"hub alias: unknown shell"` error on anything except `bundle install`.

Using the example on the puppet-ruby README, I can successfully run `bundle install`:

``` puppet
  ## Run bundle install
  exec { "bundle install app":
    provider => 'shell',
    command => "env -i bash -c 'source /opt/boxen/env.sh && RBENV_VERSION=${ruby_version} bundle install'"
    cwd => "${boxen::config::srcdir}/app",
    require => [
      Ruby::Gem["bundler for ${ruby_version}"],
      Service['postgresql']
    ],
    timeout => 1800
  }
```

However if I try to run a different command, running 'bundle check' via an `unless`:

``` puppet
  unless => "env -i bash -c 'source /opt/boxen/env.sh && RBENV_VERSION=${dabo_ruby_version} bundle check'"
```

I get a "hub alias: unknown shell" error.

```
Debug: Exec[bundle install app](provider=shell): Executing check '["/bin/sh", "-c", "env -i bash -c 'source /opt/boxen/env.sh && RBENV_VERSION=2.0.0-p353 bundle check'"]'
Debug: Executing '/bin/sh -c env -i bash -c 'source /opt/boxen/env.sh && RBENV_VERSION=2.0.0-p353 bundle check''
Debug: /Stage[main]/Projects::App/Exec[bundle install app]/unless: hub alias: unknown shell
Debug: /Stage[main]/Projects::App/Exec[bundle install app]/unless: The Gemfile's dependencies are satisfied
```

Strangely enough, bundler is reporting that dependencies are satisfied when I know they're not, so perhaps a different bundler than I think is being executed. Any help would be appreciated.

**Comment by seanknox** [comment]
@pgib Where did you install your custom Facter within your Boxen install? Should this something that `puppet-boxen` handles?

**Comment by pgib** [comment]
@seanknox I put it within the `lib/facter` of a custom module that we use for our own org-specific stuff. Just noticing that I could have put it in `$BOXEN_HOME/facts.d`. ([boxen_facts_d.rb](https://github.com/boxen/puppet-boxen/blob/master/lib/facter/boxen_facts_d.rb#L4))

It does seem like the user's shell is handy to know about in some cases, and would be good to be there by default.
