### ISSUE TITLE
rbenv global version not set

### ISSUE THREAD

**Issue by dulaccc** [boxen/puppet-ruby#86]
After declaring the global version in the `hiera/common.yaml` file, I still get the global version defined to `system`

**hiera/common.yaml**
```yaml
ruby::global::version: "2.1.0"
```
I still get

```sh
$ cd ~
$ rbenv version
system (set by /opt/boxen/rbenv/version)
```

Whereas all the ruby versions I want are available

```sh
$ rbenv versions
* system (set by /opt/boxen/rbenv/version)
  1.9.3
  1.9.3-p545
  2.0.0
  2.0.0-p353
  2.1.0
```

I believe there is something going wrong with the hiera global definition, don't you think ?

**Comment by lyzadanger** [comment]
I am also experiencing this. Unable to use hiera to set global ruby version.

**Comment by sebroeder** [comment]
It works for me in my `sebroeder.yaml`, see sebroeder/myboxen@78c809688945b0aa76d345d7cfb797328289d663.

Did you also `include ruby::global`?

**Comment by sebasoga** [comment]
@sebroeder I get a 404 on the link, maybe link to a gist?

**Comment by adamnbowen** [comment]
I can confirm that the suggestion from @sebroeder works—I've put this in my common.yaml file:

```yml
ruby::global::version: 2.2.0

ruby::rbenv::ensure: v0.4.0

ruby::build::ensure: v20150130
```

and this in my ruby.pp file I use to manage my ruby environment:

```puppet
include ruby::global
```

I can also reference the global ruby version when installing gems, such as:

```puppet
$ruby_global_version = hiera('ruby::global::version')

ruby_gem { 'shopify_theme':
  gem          => 'shopify_theme',
  ruby_version => $ruby_global_version
}
```

**Comment by dulaccc** [comment]
It's working now for me too now.
I believe it has been fixed in other commit from boxen or hiera. So I'm closing it.
Cheers
