### ISSUE TITLE
rbenv plungins support in 8.0

### ISSUE THREAD

**Issue by blackjid** [boxen/puppet-ruby#93]
In the braking changes sections it says `rbenv plugin support is gone` but in the usage section there is and example of a rbenv plugin.  Does the 8.0 version of this module still support the installation of `rbenv-vars` this way? or is something that should be removed from the readme?

```puppet
# Installing rbenv plugin
ruby::plugin { 'rbenv-vars':
  ensure => 'v1.2.0',
  source  => 'sstephenson/rbenv-vars'
}
```

**Comment by seanknox** [comment]
Closing this since #125 will be merged in soon.

**Comment by blackjid** [comment]
Great!!
