### ISSUE TITLE
Build aliases listed in hiera config not found by ruby-build

### ISSUE THREAD

**Issue by eebs** [boxen/puppet-ruby#98]
When using `ruby::version { '1.9.3': }` I get an error saying that ruby-build cannot find the definition for 1.9.3-p545. This is aliased in [common.yaml](https://github.com/boxen/puppet-ruby/blob/master/data/common.yaml#L15). It worked at one point, as I have a machine that had 1.9.3-p545 installed, but a fresh install fails.

I also uninstalled 1.9.3-p545 from the machine that had it, and I began to see the error on that machine as well. Note that other versions install without issue.

Here's a pastebin of my boxen log: http://pastebin.com/QSu8LkwC

Using puppet-ruby 7.3.0

**Comment by seanknox** [comment]
Hi @eebs, is this still an issue?

**Comment by eebs** [comment]
@seanknox I'm unfortunately not using Boxen on that machine anymore so I am unable to test the behavior. I will close this issue.
